id: "1787007774696"
alias: "Household: Last Leaves Home"
description: >-
  Closes the garage door, locks the front door, sets the living room
  thermostat to Away preset, and turns off lights, fans, and switches labeled
  "No One Is Home" when the last person leaves home. Fires when zone.home drops
  to 0 and holds for 2 minutes 30 seconds.
triggers:
  - trigger: state
    entity_id: zone.home
    to: "0"
    for:
      minutes: 2
      seconds: 30
    alias: Last person leaves home for 2 minutes 30 seconds
conditions: []
actions:
  - alias: Set living room thermostat to Away preset
    action: climate.set_preset_mode
    target:
      entity_id: climate.living_room_thermostat
    data:
      preset_mode: away
  - alias: Close garage door
    action: cover.close_cover
    target:
      entity_id: cover.garage_door_opener_door
    data: {}
  - alias: Lock front door
    action: lock.lock
    target:
      entity_id: lock.entrance_front_door
    data: {}
  - alias: Turn off lights labeled "No One Is Home"
    action: light.turn_off
    target:
      label_id: no_one_home
    data: {}
  - alias: Turn off fans labeled "No One Is Home"
    action: fan.turn_off
    target:
      label_id: no_one_home
    data: {}
  - alias: Turn off switches labeled "No One Is Home"
    action: switch.turn_off
    target:
      label_id: no_one_home
    data: {}
mode: single
category: 01M08R77W9A83G7DDA33MT8R09
